spring:
  batch:
    job:
      names: ${job.name:NONE} # job name ? ?????. job name? job configuration ?? ??? job name? ???? ???.
    initializer-schema: always # Batch? ???? SQL ??? ????? ?????. ????? ???? ????? ?????, always ??? ?? ???? ???? ?? ????? ? ????. ?? ??? ???? ???? ???.